import { STATS } from "@/content/home"
import type { HomeStat } from "@/lib/site-content"

/**
 * Track record. The numbers count up on entry and a dot grid behind them
 * ripples out; the grid itself is generated by the motion layer, which needs
 * the measured section size to know how many dots fit.
 *
 * The figures come from the CMS (Home page → Track record stats); with none
 * set the section is left out.
 */
export function Stats({ items }: { items: HomeStat[] }) {
  if (!items.length) return null

  return (
    <section className="stats" id="stats" data-surface="dark">
      <div className="stats-dots" id="statsDots" aria-hidden="true" />
      <div className="wrap">
        <p className="eyebrow" data-reveal>
          {STATS.eyebrow}
        </p>
        <div className="stats-grid">
          {items.map((stat, i) => (
            <div className="stat" data-reveal key={`${i}-${stat.label}`}>
              <b>
                <span data-count={stat.value}>0</span>
                {stat.suffix ? <sup>{stat.suffix}</sup> : null}
              </b>
              <i />
              <span>{stat.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
