import { STATS } from "@/content/home"

/**
 * Track record. The numbers count up on entry and a dot grid behind them
 * ripples out; the grid itself is generated by the motion layer, which needs
 * the measured section size to know how many dots fit.
 *
 * MOCK DATA: the four figures are illustrative and need client confirmation.
 */
export function Stats() {
  return (
    <section className="stats" id="stats" data-surface="dark">
      <div className="stats-dots" id="statsDots" aria-hidden="true" />
      <div className="wrap">
        <p className="eyebrow" data-reveal>
          {STATS.eyebrow}
        </p>
        <div className="stats-grid">
          {STATS.items.map((stat) => (
            <div className="stat" data-reveal key={stat.label}>
              <b>
                <span data-count={stat.value}>0</span>
                {stat.suffix ? <sup>{stat.suffix}</sup> : null}
              </b>
              <i />
              <span>{stat.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
